on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0

      - name: Install .NET (v6.0)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x

      - name: Build and Deploy
        run: |
          cd src/GCore.Antlr.Grammers
          dotnet run -- ${{ secrets.NUGET_TOKEN }}
          cd ../..
        
      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: doc/docfx/docfx.json
        
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/docfx/_site
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'